### ISSUE TITLE
Arbitrary keyword searching

### ISSUE THREAD

**Issue by tomrittervg** [cryptodotis/code-peer-review#10]
Allow searching through changelogs (possibly diffs) on _any_ keyword - not just the ones in the database.

**Comment by sigmavirus24** [comment]
This is potentially dangerous because I'm unsure of whether or not python has input sanitation methods.

It'd be nice if there were a built-in like php's sanitize (http://www.phpclasses.org/package/4269-PHP-Escape-values-of-request-variables.html). In our case there's no easy way to sanitize the input ourselves since a commit may quite possibly say "DROP TABLE ..." and excluding that would hinder the usefulness of this.

Unless of course you limit keyword searching to certain pre-existing tags, then searching through the change-logs based upon user-input shouldn't be too insecure. You could just use the `re` library for that and in that case we could even allow the use of regular expressions for searching (which I wish google would allow for sometimes).

**Comment by tomrittervg** [comment]
I'm relying on understanding python's DB-API interpolation.  Everything I've seen says that's the 'right way' to prevent SQL injection in python.  

http://www.mouldy.org/a-quick-guide-to-using-mysql-in-python - Explanation
https://github.com/cryptodotis/code-audit-feed/blob/master/commit.py#L113 - Example

**Comment by sigmavirus24** [comment]
I'd seen the interpolation elsewhere but wasn't sure if it applied to the MySQL module you're using.

**Comment by tomrittervg** [comment]
This is finally completed.
